name: firstTry

on: workflow_dispatch

jobs:
  basic-workflow:
    runs-on: ubuntu-latest

    steps:
      - name: CheckoutRepo
        uses: actions/checkout@v4

      - name: Print environment details
        run: env